---
abstract: 'system() and background procs w/ piping, redirs, ptys (Unix, Win32)'
author:
  - 'Barrie Slaymaker <barries@slaysys.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Readonly: '0'
  Readonly::Array: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-Run
no_index:
  directory:
    - t
    - inc
recommends:
  IO::Pty: '1.08'
requires:
  IO::Pty: '1.08'
  Test::More: '0.47'
resources:
  bugtracker: https://github.com/toddr/IPC-Run/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/toddr/IPC-Run
version: '0.97'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
