---
abstract: 'system() and background procs w/ piping, redirs, ptys (Unix, Win32)'
author:
  - 'Barrie Slaymaker <barries@slaysys.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Run
no_index:
  directory:
    - t
    - inc
recommends:
  IO::Pty: 1.08
requires:
  IO::Pty: 1.08
  Test::More: 0.47
resources:
  bugtracker: https://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-Run
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/IPC-Run
version: 0.90_01
