name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 5
      - name: perl -V
        run: perl -V
        timeout-minutes: 5
      - name: uses install-with-cpm
        uses: perl-actions/install-with-cpm@stable
        timeout-minutes: 5
        with:
          cpanfile: "cpanfile"
          # IO-Tty-1.16 exceeded 60s default
          args: "--configure-timeout=600 --with-recommends --with-suggests"
          sudo: false
      - name: Makefile.PL
        run: perl Makefile.PL
        timeout-minutes: 5
      - name: make test
        run: make test
        timeout-minutes: 5
