name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: uses install-with-cpm
        uses: perl-actions/install-with-cpm@stable
        with:
          cpanfile: "cpanfile"
          args: "--configure-timeout=600 --with-recommends --with-suggests"
          sudo: false
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test
